site_name: Tài liệu & Kiến thức lập trình
site_url: https://example.com
repo_url: https://github.com/vanphuoc9/MKDocs
edit_uri: edit/main/docs/
nav:
  - Trang chủ: index.md
  - Kubernetes (K8s):
      - Cài đặt Kubernetes cluster 1 master, 2 worker trên Ubuntu 24.04: Kubernetes (K8s)/Cài đặt K8S/Cài đặt Kubernetes cluster 1 master, 2 worker trên Ubuntu 24.04.md
      - Cài đặt NFS server: Kubernetes (K8s)/Cài đặt K8S/Cài đặt nfs.md
      - Cài đặt Ingress Nginx: Kubernetes (K8s)/Cài đặt K8S/Cài đặt ingress.md
      - Cài đặt Metallb + Ingress Nginx: Kubernetes (K8s)/Cài đặt K8S/Cài đặt Metallb.md
      - Cài đặt ArgoCD: Kubernetes (K8s)/Cài đặt K8S/Cài đặt argocd.md
      - Cài đặt Jenkins: Kubernetes (K8s)/Cài đặt K8S/Cài đặt jenkins.md
      - Mẹo: Kubernetes (K8s)/Cài đặt K8S/Tips.md
      - Lý thuyết: Kubernetes (K8s)/Cài đặt K8S/Lý thuyết.md
      - GitOps với Jenkins + Argocd + Github + Docker hub trên k8s: 
        - Giới thiệu: Kubernetes (K8s)/Gitops/Gitops.md
        - Cấu hình luồng Jenkins Build Docker image và push lên Docker Hub trên k8s: Kubernetes (K8s)/Gitops/jenkins-build-image.md
        - Cấu hình luồng Argocd deploy lên k8s: Kubernetes (K8s)/Gitops/argocd-deploy.md
        - Cấu hình toàn luồng Jenkins + Argocd + Github + Docker hub trên k8s: Kubernetes (K8s)/Gitops/full-jenkins-argocd.md
  - Dự án phim: 
    - 1. Giới thiêu: project/movie/GioiThieu.md

    - 2. Cài đặt môi trường DEV: 
      - 2.1. Cài đặt Keycloack: project/movie/keycloack.md
      - 2.2. Cài đặt Redis: project/movie/redis.md
      - 2.3. Cài đặt MongoDB: project/movie/mongodb.md
  - Liên hệ: Liên hệ/index.md
  - Blog: 
      - blog/index.md

theme:
  icon:
    edit: material/pencil 
    view: material/eye
  language: vi
  name: material
  custom_dir: overrides
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: deep orange
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share
    - navigation.indexes
    - content.code.copy
    - content.action.view
    - content.action.edit
    
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
copyright: Copyright &copy; 2025 Thái Văn Phước
plugins:
  - glightbox
  - search
  - blog:
      archive_date_format: MMMM yyyy
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
extra:
  analytics:
    provider: google
    property: G-D8WJRZCBNB
    feedback:
      title: Bài viết có hữu ích cho bạn không?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Có hữu ích
          data: 1
          note: >-
            Cảm ơn bạn đã phản hồi!
        - icon: material/emoticon-sad-outline
          name: Không hữu ích
          data: 0
          note: >- 
            Cảm ơn đã phản hồi! Hãy giúp chúng tôi cải thiện trang này bằng cách điền vào mẫu
             <a href="https://docs.google.com/forms/d/e/1FAIpQLSfxXARl33b7ul3h0onQ2PeUG_1ouXuZnlTUOhRURmAD8MUh0Q/viewform?usp=dialog" target="_blank" rel="noopener">Mãu phản hồi</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vanphuoc9
    - icon: fontawesome/brands/telegram
      link:  https://t.me/tvphuoctgg  
#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: Tiếng Việt
#       link: /vi/
#       lang: vi
    

