site_name: Tài liệu & Kiến thức lập trình
site_url: https://example.com
repo_url: https://github.com/vanphuoc9/MKDocs
edit_uri: edit/main/docs/
theme:
  icon:
    edit: material/pencil 
    view: material/eye
  language: vi
  name: material
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: deep orange
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share
    - navigation.indexes
    - content.code.copy
    - content.action.view
    - content.action.edit
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
copyright: Copyright &copy; 2025 Thái Văn Phước
plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vanphuoc9
    - icon: fontawesome/brands/telegram
      link:  https://t.me/tvphuoctgg  
#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: Tiếng Việt
#       link: /vi/
#       lang: vi
    

